### ISSUE TITLE
Can't Locate Repos in Folders

### ISSUE THREAD

**Issue by alexlafroscia** [cjlucas/tower-alfred-workflow#11] opened 2015-06-03 19:32 UTC
If seems like this workflow can't find any repos that are nested inside of a folder in Tower's UI

![screen_shot_2015-06-03_at_3_32_43_pm](https://cloud.githubusercontent.com/assets/1645881/7969628/2eb80b30-0a06-11e5-86bd-0eb00836691f.png)

**Comment by elalemanyo** [comment] 2015-06-29 07:33
Hi,
I am having the same problem, but I think that something changed since the last update from tower.
Maybe tower changed something...

**Comment by jCrip** [comment] 2015-07-24 15:59
sam ehere

**Comment by mattstein** [comment] 2015-07-28 16:46
I can confirm this as well with Tower 2.3.0 (Build 292) and the same behavior with the latest beta release.

**Comment by jb510** [comment] 2015-08-05 23:45
Same... but I'm pretty sure it's been like that since T2 and folders...  Would be nice to fix.

**Comment by jb510** [comment] 2015-08-06 06:45
Worth noting... looking at the bookmarks_parser it looks like it's supposed to traverse folders, but then I don't know enough Ruby to guess why it's not working.

**Comment by cjlucas** [comment] 2015-08-08 02:03
Sorry for the late response on this, The commit above should fix it. Can someone please pull the latest master and test it out. You should only have to copy the `net.cjlucas.alfred.tower` directory into your Alfred preferences file (under `workflows/`).

**Comment by elalemanyo** [comment] 2015-08-08 07:54
Now works great!
Thanks!

**Comment by mattstein** [comment] 2015-08-08 19:11
Lovely, thanks @cjlucas!

**Comment by jb510** [comment] 2015-08-08 19:22
+1 on working now.  Ty!

**Comment by alexlafroscia** [comment] 2015-08-09 00:35
@cjlucas will you bundle/release a new version with the fix?

**Comment by cjlucas** [comment] 2015-08-09 19:27
Thanks all. v2.4 has been released with this fix.

**Closed by cjlucas** 2015-08-09 19:27 UTC
